# Generated by Django 4.2.5 on 2024-06-29 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='카테고리명')),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='FrontCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='프론트 카테고리명')),
            ],
            options={
                'verbose_name': '프론트 카테고리',
                'verbose_name_plural': '프론트 카테고리',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='MarketingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='마케팅 카테고리명')),
                ('display_order', models.IntegerField(default=0, verbose_name='진열 순서')),
            ],
            options={
                'verbose_name': '마케팅 카테고리',
                'verbose_name_plural': '마케팅 카테고리',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='assets/products', verbose_name='이미지')),
            ],
            options={
                'verbose_name': '상품 이미지',
                'verbose_name_plural': '상품 이미지',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='태그명')),
            ],
            options={
                'verbose_name': '태그',
                'verbose_name_plural': '태그',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, verbose_name='상품 UUID')),
                ('manufacturer', models.CharField(choices=[('INTEL', 'INTEL'), ('AMD', 'AMD')], default='INTEL', max_length=6, verbose_name='제조사')),
                ('code_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='코드네임')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='상품명')),
                ('age', models.CharField(blank=True, max_length=100, null=True, verbose_name='세대')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='모델명')),
                ('cores', models.IntegerField(blank=True, null=True, verbose_name='코어')),
                ('threads', models.IntegerField(blank=True, null=True, verbose_name='스레드')),
                ('base_clock_rate_ghz', models.FloatField(blank=True, null=True)),
                ('turbo_boost_clock_rate_ghz', models.FloatField(blank=True, null=True)),
                ('gpu_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='GPU 모델')),
                ('launch_year', models.IntegerField(blank=True, null=True, verbose_name='출시년도')),
                ('currency', models.CharField(choices=[('KRW', 'KRW'), ('USD', 'USD'), ('JPY', 'JPY'), ('EUROS', 'EUROS')], default='KRW', max_length=6, verbose_name='통화')),
                ('price', models.IntegerField(default=0, verbose_name='가격')),
                ('description', models.TextField(blank=True, null=True, verbose_name='설명')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='assets/thumbnails', verbose_name='썸네일')),
                ('is_display', models.BooleanField(default=True, verbose_name='진열여부')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_products', to='products.category')),
                ('detail_images', models.ManyToManyField(blank=True, related_name='image_products', to='products.productimage')),
                ('frontcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frontcategory_products', to='products.frontcategory')),
                ('marketing_categories', models.ManyToManyField(blank=True, related_name='marketing_products', to='products.marketingcategory')),
                ('tags', models.ManyToManyField(blank=True, related_name='tag_products', to='products.tag')),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품',
                'ordering': ['-created_on'],
                'unique_together': {('uuid',)},
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='제목')),
                ('content', models.TextField(blank=True, null=True, verbose_name='내용')),
                ('rating', models.FloatField(default=0, verbose_name='평점')),
                ('image', models.ImageField(blank=True, null=True, upload_to='assets/reviews', verbose_name='리뷰 이미지')),
                ('is_display', models.BooleanField(default=True, verbose_name='진열여부')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.products')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '상품 리뷰',
                'verbose_name_plural': '상품 리뷰',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='브랜드명')),
                ('image', models.ImageField(blank=True, null=True, upload_to='assets/brands', verbose_name='브랜드 이미지')),
                ('description', models.TextField(blank=True, null=True, verbose_name='설명')),
                ('searchtags', models.ManyToManyField(related_name='brands', to='products.tag')),
            ],
            options={
                'verbose_name': '브랜드',
                'verbose_name_plural': '브랜드',
                'ordering': ['name'],
            },
        ),
    ]
