# Generated by Django 4.2.5 on 2024-06-29 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='products',
            name='price',
        ),
    ]
