# Generated by Django 4.2.5 on 2024-06-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_products_currency_remove_products_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='products',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='products',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='모델명'),
        ),
        migrations.AlterField(
            model_name='products',
            name='uuid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='상품 UUID'),
        ),
    ]
