# Generated by Django 4.2.5 on 2024-06-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_products_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='memorysize',
            field=models.IntegerField(blank=True, null=True, verbose_name='메모리 크기'),
        ),
        migrations.AlterField(
            model_name='products',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='제조사'),
        ),
    ]
