# Generated by Django 4.2.5 on 2024-07-01 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_products_memorysize_alter_products_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='memoryversion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='메모리 종류'),
        ),
    ]
