# Generated by Django 4.2.5 on 2024-07-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_products_memoryversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='fromfactor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='폼팩터'),
        ),
    ]
