# Generated by Django 4.2.5 on 2024-07-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_products_fromfactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='memorycompatibility',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='메모리 호환성'),
        ),
    ]
