# Generated by Django 4.2.5 on 2024-07-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_products_memorycompatibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='fromfactor',
        ),
        migrations.AddField(
            model_name='products',
            name='formfactor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='폼팩터'),
        ),
    ]
