# Generated by Django 4.2.5 on 2024-07-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_products_fromfactor_products_formfactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='harddrivesize',
            field=models.IntegerField(blank=True, null=True, verbose_name='하드디스크 크기'),
        ),
    ]
