# Generated by Django 4.2.5 on 2024-07-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_products_harddrivesize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='harddrivesize',
            field=models.CharField(blank=True, null=True, verbose_name='하드디스크 크기'),
        ),
    ]
