# Generated by Django 4.2.5 on 2024-07-01 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_products_harddrivesize'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='제조사명')),
                ('image', models.ImageField(blank=True, null=True, upload_to='assets/manufacturer', verbose_name='제조사 이미지')),
                ('description', models.TextField(blank=True, null=True, verbose_name='설명')),
                ('searchtags', models.ManyToManyField(related_name='manufacturer_tags', to='products.tag')),
            ],
            options={
                'verbose_name': '제조사',
                'verbose_name_plural': '제조사',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
