# Generated by Django 4.2.5 on 2024-07-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_category_subname'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingcategory',
            name='subname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='서브마케팅 카테고리명'),
        ),
    ]
