# Generated by Django 4.2.5 on 2024-07-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_marketingcategory_subname'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='wallimage',
            field=models.ImageField(blank=True, null=True, upload_to='assets/manufacturer', verbose_name='대표 이미지'),
        ),
    ]
