# Generated by Django 4.2.5 on 2024-07-03 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_manufacturer_wallimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='manufacturer',
            new_name='manufacturername',
        ),
    ]
