# Generated by Django 4.2.5 on 2024-07-03 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_rename_manufacturer_products_manufacturername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='manufacturername',
        ),
    ]
