# Generated by Django 4.2.5 on 2024-07-03 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_remove_products_manufacturername'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='manufacturerfk',
            new_name='manufacturer',
        ),
    ]
