# Generated by Django 4.2.5 on 2024-05-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_userevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevent',
            name='object_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='object uuid'),
        ),
    ]
