# Generated by Django 4.2.5 on 2024-05-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_alter_userevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevent',
            name='event_type',
            field=models.CharField(choices=[('prepandready', '페이지 로드'), ('exterminate', '페이지 닫기'), ('fiwjfwu9', '페이지 전환'), ('wolfwolf', '클릭'), ('fufu', '폼 제출'), ('a8sg4a8e4h9a', '터치 시작'), ('8ef8413f13', '터치 중'), ('ef88s84f8', '터치 끝')], max_length=50, verbose_name='이벤트 분류'),
        ),
    ]
