# Generated by Django 4.2.5 on 2024-06-14 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0010_alter_userevent_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 주소')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, verbose_name='세션 키')),
                ('visit_url', models.URLField(blank=True, null=True, verbose_name='방문 URL')),
                ('referer_url', models.URLField(blank=True, null=True, verbose_name='참조 URL')),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True, verbose_name='사용자 에이전트')),
                ('ua_platform', models.CharField(blank=True, max_length=255, null=True, verbose_name='플랫폼')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viewed_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '게시글 조회',
                'verbose_name_plural': '게시글 조회 목록',
                'ordering': ['created_on'],
            },
        ),
    ]
