# Generated by Django 4.2.5 on 2024-06-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='visit_url',
            field=models.TextField(blank=True, null=True, verbose_name='방문 URL'),
        ),
    ]
