# Generated by Django 4.2.5 on 2024-06-10 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlingUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('instock', models.BooleanField(default=False)),
                ('stockdata', models.JSONField(null=True)),
            ],
            options={
                'db_table': 'crawling_urls',
                'managed': True,
            },
        ),
    ]
