# Generated by Django 4.2.5 on 2024-06-20 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_crawlingurl_article_created_crawlingurl_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlingurl',
            name='commentno',
            field=models.IntegerField(default=0),
        ),
    ]
