# Generated by Django 4.2.5 on 2024-03-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='username')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_subscribed', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('nickname', models.CharField(blank=True, max_length=20, null=True, verbose_name='닉네임')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='연락처')),
                ('tribe', models.CharField(blank=True, choices=[('NEW', '신입'), ('DESIGNER', '디자이너'), ('CONSTRUCTION_WORKER', '시공직원'), ('DRIVER', '배송직원'), ('CS_STAFF', '고객센터 직원'), ('3D_DESIGNER', '3D 디자이너'), ('SALES', '영업직원'), ('MARKETING', '마케팅직원'), ('MANAGEMENT', '경영진'), ('CUSTOMER', '고객')], default='NEW', max_length=25, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('profile_image', models.ImageField(blank=True, default='default_profile.png', null=True, upload_to='media/avator', verbose_name='profile_image')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('access_token', models.CharField(blank=True, max_length=255, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=255, null=True)),
                ('privacyconscent', models.BooleanField(default=False)),
                ('termsconscent', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자 목록',
            },
        ),
    ]
