# Generated by Django 4.2.5 on 2024-03-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_remove_user_name_user_type_alter_user_tribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default=1, max_length=20, unique=True, verbose_name='닉네임'),
            preserve_default=False,
        ),
    ]
