# Generated by Django 4.2.5 on 2024-03-15 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_alter_user_nickname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_staff',
            new_name='is_phoneverified',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_subscribed',
            new_name='is_privacyconscent',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='privacyconscent',
            new_name='is_termsconscent',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='termsconscent',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='주소'),
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='직장명'),
        ),
        migrations.AddField(
            model_name='user',
            name='detailaddress',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='상세주소'),
        ),
        migrations.AddField(
            model_name='user',
            name='invitecode',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='초대코드'),
        ),
        migrations.AddField(
            model_name='user',
            name='jobfield',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='직군'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='연락처'),
        ),
    ]
