# Generated by Django 4.2.5 on 2024-03-17 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_rename_is_phoneverified_user_is_smsverified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_privacyconscent',
            new_name='is_privacyconsent',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_termsconscent',
            new_name='is_termsconsent',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_thirdpartyconscent',
            new_name='is_thirdpartyconsent',
        ),
    ]
