# Generated by Django 4.2.5 on 2024-03-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_rename_is_privacyconscent_user_is_privacyconsent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personalitychips',
            field=models.TextField(blank=True, null=True),
        ),
    ]
