# Generated by Django 4.2.5 on 2024-03-18 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_user_personalitychips'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowYourKidsTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('kidname', models.CharField(max_length=20, verbose_name='아이 이름')),
                ('kidbirthday', models.CharField(max_length=10, verbose_name='아이 생일')),
                ('gender', models.CharField(max_length=10, verbose_name='아이 성별')),
                ('personalitychips', models.JSONField()),
                ('answers', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '유저 테스트',
                'verbose_name_plural': '유저 테스트 목록',
                'ordering': ['created_on'],
            },
        ),
    ]
