# Generated by Django 4.2.5 on 2024-03-19 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_knowyourkidstest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='닉네임'),
        ),
    ]
