# Generated by Django 4.2.5 on 2024-03-19 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_alter_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowyourkidstest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowyourkidstest', to=settings.AUTH_USER_MODEL),
        ),
    ]
