# Generated by Django 4.2.5 on 2024-03-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0012_alter_knowyourkidstest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowyourkidstest',
            name='uuid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='UUID'),
        ),
        migrations.AlterUniqueTogether(
            name='knowyourkidstest',
            unique_together={('user', 'uuid')},
        ),
    ]
