# Generated by Django 4.2.5 on 2024-03-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0013_knowyourkidstest_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.CharField(default=1, max_length=255, verbose_name='UUID'),
            preserve_default=False,
        ),
    ]
