# Generated by Django 4.2.5 on 2024-03-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0015_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='0c1a7fca-4f00-4b6f-b705-ca44521d94de', max_length=36, verbose_name='UUID'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('name', 'phone', 'uuid')},
        ),
    ]
