# Generated by Django 4.2.5 on 2024-03-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0016_alter_user_unique_together_alter_user_uuid_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='user',
            name='uservid',
            field=models.CharField(default='8daf6afc-22e5-42cf-a1ba-04d920f54136', max_length=36, verbose_name='USERVID'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('name', 'phone', 'uservid')},
        ),
        migrations.RemoveField(
            model_name='user',
            name='uuid',
        ),
    ]
