# Generated by Django 4.2.5 on 2024-03-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0017_alter_user_unique_together_user_uservid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowyourkidstest',
            name='uuid',
            field=models.CharField(default='ef477344-3607-46f1-a7c3-759219ae98e0', max_length=255, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uservid',
            field=models.CharField(default='98cf506c-ae98-4dc5-82f5-b115ff058730', max_length=36, verbose_name='USERVID'),
        ),
    ]
