# Generated by Django 4.2.5 on 2024-03-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0018_alter_knowyourkidstest_uuid_alter_user_uservid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tribe',
        ),
        migrations.RemoveField(
            model_name='user',
            name='type',
        ),
        migrations.AddField(
            model_name='knowyourkidstest',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knowyourkidstest',
            name='keywords',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knowyourkidstest',
            name='tribe',
            field=models.CharField(blank=True, choices=[('fish', '물고기'), ('butterfly', '나비'), ('beetle', '풍뎅이'), ('owl', '부엉이'), ('tiger', '호랑이'), ('dolphin', '돌고래'), ('horse', '말'), ('wolf', '늑대')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='knowyourkidstest',
            name='tribeimg',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='유형 이미지'),
        ),
        migrations.AddField(
            model_name='knowyourkidstest',
            name='type',
            field=models.CharField(blank=True, choices=[('water', '물'), ('gold', '금속'), ('fire', '불'), ('wood', '나무'), ('earth', '흙'), ('cloud', '구름'), ('star', '별')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='knowyourkidstest',
            name='uuid',
            field=models.CharField(default='3c4fc8d2-dc34-49ef-8659-5408c515f955', max_length=255, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uservid',
            field=models.CharField(default='f350dc79-0185-467b-a377-0d37cee48a33', max_length=36, verbose_name='USERVID'),
        ),
    ]
