# Generated by Django 4.2.5 on 2024-03-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0020_rename_tribeimg_knowyourkidstest_tribe_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowyourkidstest',
            name='type',
            field=models.CharField(blank=True, choices=[('water', '물'), ('gold', '금속'), ('fire', '불'), ('tree', '나무'), ('earth', '흙'), ('cloud', '구름'), ('star', '별')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='knowyourkidstest',
            name='uuid',
            field=models.CharField(default='a266faa1-c8aa-4a80-8a30-e8e017174a9a', max_length=255, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uservid',
            field=models.CharField(default='d7825072-5513-44d7-911c-f4bfd5bb9244', max_length=36, verbose_name='USERVID'),
        ),
    ]
