# Generated by Django 4.2.5 on 2024-03-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0021_alter_knowyourkidstest_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowyourkidstest',
            name='personalityType',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='knowyourkidstest',
            name='uuid',
            field=models.CharField(default='47f8b1e3-5a6f-46f3-8616-06925d7ee448', max_length=255, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uservid',
            field=models.CharField(default='1cf952d0-7a91-44ff-8d69-e6c2112133b9', max_length=36, verbose_name='USERVID'),
        ),
    ]
