# Generated by Django 4.2.5 on 2024-03-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0022_knowyourkidstest_personalitytype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avator', verbose_name='프로필 이미지'),
        ),
        migrations.AlterField(
            model_name='knowyourkidstest',
            name='uuid',
            field=models.CharField(default='4bcf1a5e-27cd-4fed-a7cf-807b22a4d6e4', max_length=255, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uservid',
            field=models.CharField(default='e26c4ad3-1030-4184-a784-03698335e9ed', max_length=36, verbose_name='USERVID'),
        ),
    ]
