# Generated by Django 4.2.5 on 2024-03-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0023_user_avatar_alter_knowyourkidstest_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowyourkidstest',
            name='uuid',
            field=models.CharField(default='5d824ac0-6ed1-49f1-bbf7-607ce9e93b26', max_length=255, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uservid',
            field=models.CharField(default='17c85b01-ee32-47b1-8096-b8d787290a5c', max_length=36, verbose_name='USERVID'),
        ),
    ]
