# Generated by Django 4.2.5 on 2024-03-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0024_alter_knowyourkidstest_uuid_alter_user_uservid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowyourkidstest',
            name='uuid',
            field=models.CharField(default='a145b22a-519c-4489-ac30-4da8e74fcf0f', max_length=255, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uservid',
            field=models.CharField(default='cd6a7ef8-64ea-4ded-9976-2f00e9a3224d', max_length=36, verbose_name='USERVID'),
        ),
    ]
