# Generated by Django 4.2.5 on 2024-03-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0025_alter_knowyourkidstest_uuid_alter_user_uservid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowyourkidstest',
            name='uuid',
            field=models.CharField(default='9c79fb4f-139b-410b-a0de-979f30c6851d', max_length=255, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uservid',
            field=models.CharField(default='da5540c9-4bcb-4202-9ab9-04c59daa6a16', max_length=36, verbose_name='USERVID'),
        ),
    ]
