# Generated by Django 4.2.5 on 2024-03-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0027_alter_knowyourkidstest_uuid_alter_user_uservid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowyourkidstest',
            name='uuid',
            field=models.CharField(default='0d081694-04c0-4fe4-8af6-76c5f01f7cd9', max_length=255, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uservid',
            field=models.CharField(default='7c8e4064-9da6-420a-9f24-44c0fccdcd1b', max_length=36, verbose_name='USERVID'),
        ),
    ]
