# Generated by Django 4.2.5 on 2024-03-21 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0029_alter_knowyourkidstest_uuid_alter_user_uservid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowyourkidstest',
            name='uuid',
            field=models.CharField(default='123fef80-e9ad-491e-a2f4-d356232ad069', max_length=255, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uservid',
            field=models.CharField(default='aa131268-9f54-4fc8-8188-1f463a962761', max_length=36, verbose_name='USERVID'),
        ),
    ]
