# Generated by Django 4.2.5 on 2024-03-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0031_remove_knowyourkidstest_tribe_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowyourkidstest',
            name='uuid',
            field=models.CharField(default='8165b107-31bd-4103-952c-ec5afb8344ec', max_length=255, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uservid',
            field=models.CharField(default='73f328cc-e40c-4c06-bf5d-388861e1ffc1', max_length=36, verbose_name='USERVID'),
        ),
    ]
