# Generated by Django 4.2.5 on 2024-03-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0032_alter_knowyourkidstest_uuid_alter_user_uservid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='curr',
            field=models.CharField(default='KRW', max_length=3, verbose_name='통화'),
        ),
        migrations.AlterField(
            model_name='knowyourkidstest',
            name='uuid',
            field=models.CharField(default='52e94e4a-1ce4-4619-ac80-87396b6fcd4d', max_length=255, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uservid',
            field=models.CharField(default='1625e766-7618-43ce-a60b-4c4658f3905e', max_length=36, verbose_name='USERVID'),
        ),
    ]
