# Generated by Django 4.2.5 on 2024-03-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0033_user_curr_alter_knowyourkidstest_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='refresh_token',
        ),
        migrations.AlterField(
            model_name='knowyourkidstest',
            name='uuid',
            field=models.CharField(default='dd975a7c-ecea-4baa-a61a-1e65e881fb0e', max_length=255, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uservid',
            field=models.CharField(default='4d1b46dc-bd41-419a-983e-5b0524258c78', max_length=36, verbose_name='USERVID'),
        ),
    ]
