# Generated by Django 4.2.5 on 2024-03-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0034_remove_user_access_token_remove_user_refresh_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowyourkidstest',
            name='uuid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uservid',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='USERVID'),
        ),
    ]
