# Generated by Django 4.2.5 on 2024-03-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0035_alter_knowyourkidstest_uuid_alter_user_uservid'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='user',
            name='hash_phone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='b연락처'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('name', 'hash_phone', 'uservid')},
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
