# Generated by Django 4.2.5 on 2024-03-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0038_keyword_user_introduction_user_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('adminid', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
