# Generated by Django 4.2.5 on 2024-03-23 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0039_adminuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminUser',
        ),
    ]
