# Generated by Django 4.2.5 on 2024-03-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0040_delete_adminuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_thirdpartyconsent2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='가입일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='어드민유저'),
        ),
    ]
