# Generated by Django 4.2.5 on 2024-03-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0041_user_is_thirdpartyconsent2_alter_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='raw_phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='연락처'),
        ),
    ]
