# Generated by Django 4.2.5 on 2024-04-03 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0042_user_raw_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uservid',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='uservid'),
        ),
    ]
