# Generated by Django 4.2.5 on 2024-04-05 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0043_alter_user_uservid'),
        ('member', '0043_remove_user_keywords_user_keywords'),
    ]

    operations = [
    ]
