# Generated by Django 4.2.5 on 2024-04-06 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0044_merge_20240405_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_termsconsent',
        ),
    ]
