# Generated by Django 4.2.5 on 2024-04-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0045_remove_user_is_termsconsent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='이메일'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='default_profile.png', null=True, upload_to='snsavator', verbose_name='profile_image'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_nickname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='profile_nickname'),
        ),
        migrations.AddField(
            model_name='user',
            name='provider',
            field=models.CharField(blank=True, choices=[('kakao', '카카오'), ('naver', '네이버'), ('facebook', '페이스북'), ('google', '구글'), ('apple', '애플')], max_length=20, null=True, verbose_name='소셜채널'),
        ),
        migrations.AddField(
            model_name='user',
            name='verifiedname',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='본인인증된 이름'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='닉네임'),
        ),
    ]
