# Generated by Django 4.2.5 on 2024-04-06 18:33

from django.db import migrations, models
import member.models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0046_remove_user_nickname_user_email_user_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uservid',
            field=models.CharField(blank=True, default=member.models.get_uuid, max_length=36, null=True, verbose_name='uservid'),
        ),
    ]
