# Generated by Django 4.2.5 on 2024-04-07 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0047_alter_user_uservid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verifiedname',
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='닉네임'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='본인인증된 이름'),
        ),
    ]
