# Generated by Django 4.2.5 on 2024-04-07 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0048_remove_user_verifiedname_user_nickname_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('nickname', 'hash_phone', 'uservid')},
        ),
    ]
