# Generated by Django 4.2.5 on 2024-04-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0050_alter_user_nickname'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, default='user84327', max_length=255, null=True, unique=True, verbose_name='닉네임'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('nickname', 'hash_phone', 'uservid', 'email')},
        ),
    ]
