# Generated by Django 4.2.5 on 2024-04-08 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0051_alter_user_unique_together_alter_user_nickname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, default='user30cf0', max_length=255, null=True, unique=True, verbose_name='닉네임'),
        ),
    ]
