# Generated by Django 4.2.5 on 2024-04-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0052_alter_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, default='user29b09', max_length=255, null=True, unique=True, verbose_name='닉네임'),
        ),
    ]
