# Generated by Django 4.2.5 on 2024-04-09 08:40

from django.db import migrations, models
import member.models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0053_alter_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, default=member.models.get_random_nickname, max_length=255, null=True, unique=True, verbose_name='닉네임'),
        ),
    ]
