# Generated by Django 4.2.5 on 2024-04-09 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0055_user__is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False, 'ordering': ['date_joined'], 'verbose_name': '사용자', 'verbose_name_plural': '사용자 목록'},
        ),
    ]
