# Generated by Django 4.2.5 on 2024-04-12 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0057_alter_user_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowyourkidstest',
            name='keywords',
        ),
    ]
