# Generated by Django 4.2.5 on 2024-04-14 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0060_remove_user_invitecode_user_invitationcode_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Keyword',
        ),
        migrations.DeleteModel(
            name='KnowYourKidsTest',
        ),
    ]
