# Generated by Django 4.2.5 on 2024-05-05 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0061_delete_keyword_delete_knowyourkidstest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('uuid', models.CharField(blank=True, max_length=36, null=True, verbose_name='UUID')),
                ('name', models.CharField(max_length=255, verbose_name='팀명')),
                ('description', models.TextField(blank=True, null=True, verbose_name='팀 설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader_team', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='team_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
