# Generated by Django 4.2.5 on 2024-05-05 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0063_alter_team_options_user_teams_alter_team_leader_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
    ]
