# Generated by Django 4.2.5 on 2024-05-06 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0065_team_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['-created_on'], 'verbose_name': '팀', 'verbose_name_plural': '팀 목록'},
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='assets/avator', verbose_name='프로필 이미지'),
        ),
    ]
