# Generated by Django 4.2.5 on 2024-05-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0066_alter_team_options_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='invitecode',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='초대코드'),
        ),
    ]
