# Generated by Django 4.2.5 on 2024-05-10 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0068_alter_team_leader'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('name', 'leader')},
        ),
    ]
