# Generated by Django 4.2.5 on 2024-06-26 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0069_alter_team_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='image',
        ),
    ]
