# Generated by Django 4.2.5 on 2024-03-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
        migrations.AlterField(
            model_name='article',
            name='uuid',
            field=models.CharField(default='23094c14', max_length=255, verbose_name='UUID'),
        ),
    ]
