# Generated by Django 4.2.5 on 2024-03-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_remove_comment_title_alter_article_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='uuid',
            field=models.CharField(default='0a62ed80', max_length=255, verbose_name='UUID'),
        ),
    ]
