# Generated by Django 4.2.5 on 2024-03-20 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_alter_article_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_article', to='article.article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='uuid',
            field=models.CharField(default='a3299853', max_length=255, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_image', to='article.article'),
        ),
    ]
