# Generated by Django 4.2.5 on 2024-03-21 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_like_view_remove_articleview_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='uuid',
            field=models.CharField(default='2fbfb306', max_length=255, verbose_name='UUID'),
        ),
    ]
