# Generated by Django 4.2.5 on 2024-04-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0020_alter_like_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='article/', verbose_name='이미지(예정)'),
        ),
    ]
