# Generated by Django 4.2.5 on 2024-04-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0023_notice_is_active_view_ip_address_view_referrer_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='visit_url',
            field=models.URLField(blank=True, null=True, verbose_name='방문 URL'),
        ),
    ]
