# Generated by Django 4.2.5 on 2024-04-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0031_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleimage',
            name='article',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='이미지'),
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ManyToManyField(blank=True, null=True, related_name='image_article', to='article.articleimage'),
        ),
    ]
