# Generated by Django 4.2.5 on 2024-04-29 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0033_alter_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleimage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_images', to=settings.AUTH_USER_MODEL),
        ),
    ]
