# Generated by Django 4.2.5 on 2024-04-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0036_alter_articleimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='assets/thumbnails/', verbose_name='썸네일'),
        ),
    ]
