# Generated by Django 4.2.5 on 2024-05-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0037_remove_article_image_article_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, default='https://via.placeholder.com/80x80', null=True, upload_to='assets/thumbnails', verbose_name='썸네일'),
        ),
    ]
