# Generated by Django 4.2.5 on 2024-05-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0038_alter_article_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_editorcontent',
            field=models.BooleanField(default=False, verbose_name='에디터 컨텐츠 여부'),
        ),
    ]
