# Generated by Django 4.2.5 on 2024-05-21 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0039_article_is_editorcontent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on'], 'verbose_name': '댓글', 'verbose_name_plural': '댓글 목록'},
        ),
    ]
