# Generated by Django 4.2.5 on 2024-05-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0041_alter_article_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='uuid',
            field=models.CharField(blank=True, null=True, verbose_name='UUID'),
        ),
    ]
