# Generated by Django 4.2.5 on 2024-06-10 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0043_alter_article_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['created_on'], 'verbose_name': '게시글', 'verbose_name_plural': '게시글 목록'},
        ),
    ]
