# Generated by Django 4.2.5 on 2024-06-14 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0044_alter_article_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='View',
        ),
    ]
