# Generated by Django 4.2.5 on 2024-06-16 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0045_delete_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='tag_article', to='article.tag'),
        ),
    ]
