# Generated by Django 4.2.5 on 2024-06-29 21:05

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_alter_products_unique_together_alter_products_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiddingImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='assets/bids', verbose_name='이미지')),
            ],
            options={
                'verbose_name': '입찰 이미지',
                'verbose_name_plural': '입찰 이미지',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='CatchyTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='태그명')),
            ],
            options={
                'verbose_name': '입찰 태그',
                'verbose_name_plural': '입찰 태그',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('uuid', models.CharField(blank=True, max_length=36, null=True, verbose_name='UUID')),
                ('price', models.IntegerField(default=0, verbose_name='가격')),
                ('score', models.IntegerField(choices=[(100, 100), (95, 95), (90, 90), (85, 85)], default=90, verbose_name='상태 점수')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='거래 위치')),
                ('is_sold', models.BooleanField(default=False, verbose_name='품절 여부')),
                ('is_active', models.BooleanField(default=False, verbose_name='판매승인 여부')),
                ('content', models.TextField(verbose_name='상세 설명')),
                ('catchy_tags', models.ManyToManyField(blank=True, related_name='tags_bids', to='bids.catchytags')),
                ('images', models.ManyToManyField(blank=True, related_name='images_bids', to='bids.biddingimages')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_bids', to='products.products', to_field='uuid')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_bids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '입찰',
                'verbose_name_plural': '입찰',
                'ordering': ['-score'],
            },
        ),
    ]
