# Generated by Django 4.2.5 on 2024-06-18 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0002_alter_inquiry_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
