# Generated by Django 4.2.5 on 2024-04-03 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ['order'], 'verbose_name': '광고', 'verbose_name_plural': '광고'},
        ),
    ]
