# Generated by Django 4.2.5 on 2024-04-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_ad_image_alter_ad_is_active_alter_ad_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(upload_to='ads/', verbose_name='이미지 (327x90) (필수)'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='순서 (필수)'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='제목 (필수)'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='링크 (필수)'),
        ),
    ]
