# Generated by Django 4.2.5 on 2024-04-10 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_alter_ad_image_alter_ad_order_alter_ad_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='활성화'),
        ),
    ]
